apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-qa-rag.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "document-qa-rag.fullname" . }}-config
            - secretRef:
                name: {{ include "document-qa-rag.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
