{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "document-qa-rag.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressPodSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
{{- end }}
