{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "document-qa-rag.fullname" . }}-postgresql
spec:
  serviceName: {{ include "document-qa-rag.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}-postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ragdb
            - name: POSTGRES_USER
              value: {{ .Values.app.datasourceUsername | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "document-qa-rag.fullname" . }}-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-qa-rag.fullname" . }}-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}-postgresql
{{- end }}
