{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-qa-rag.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-qa-rag.fullname" . }}-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: {{ include "document-qa-rag.name" . }}-redis
{{- end }}
