apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-qa-rag.fullname" . }}-secret
type: Opaque
stringData:
  APP_JWT_SECRET: {{ .Values.app.jwtSecret | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.app.datasourcePassword | quote }}
  OPENAI_API_KEY: {{ .Values.app.openAiApiKey | quote }}
